trigger:
- master

stages:
- stage: First-Stage
  jobs:
  - job: First-job
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - script: echo "First Stage job"
- stage: Second-Stage
  jobs:
  - job: second-job
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - script: echo "Second stage job"
