trigger:
- master

stages:
- stage: Mavenjob
  jobs:
  - job: Clean_and_Package_job
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - script: echo "Clean and Package job"
    - script: mvn clean package
    - script: mv /home/vsts/work/1/s/target/webAPP.war /home/vsts/work/1/a/webAPP.war
  - job: Publishes_Artifacts
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - task: CopyFiles@2
      inputs:
        contents: 'target/*'
        targetFolder: $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: SampleWebApp
