trigger:
- master

stages:
- stage: Maven jobs 
  jobs:
  - job: Clean and Package job
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - script: echo "Clean and Package job"
    - script: mvn clean package
