trigger:
- master

stages:
- stage: Mavenjobs 
  jobs:
  - job: Clean_and_Package job
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - script: echo "Clean and Package job"
    - script: mvn clean package
