trigger:
- master

jobs:
- job: First_job
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - script: echo "First Stage job"

- job: second_job
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - script: echo "Second stage job"
