trigger:
- master

stages:
- stage: First_Stage
  jobs:
  - job: First_job
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - script: echo "First Stage job"
- stage: Second_Stage
  jobs:
  - job: second_job
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - script: echo "Second stage job"
